#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#      database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/UserAccountDB"
#    username: postgres
#    password: Azerbaycan1234
#    driverClassName: org.postgresql.Driver

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver


jwt:
  secret: tanimo
